#!/usr/bin/env python3
"""
Dynamic Watchlist Manager v2.1

Syncs the website watchlist directly from the trading bot's signal engine.
Now driven by readiness_score (not total_score) for tier assignment.

Logic:
- Read /opt/stonk-ai/signals.json (generated by signal_engine.py v2.5+)
- Take the top N symbols by readiness_score
- Assign action-based tiers:
    PRIME:    entry_eligible (readiness >= 77, >= 5 conf, above_ema)
    BUILDING: not entry_eligible, but readiness >= 55
    TRACKING: readiness < 55
- Track tier changes (promote/demote events with timestamp + reason)
- Write ai_watchlist_live.json and watchlist_changes.json for the website
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from alpaca_data import get_data_hub
from readiness_score import (
    ENTRY_MIN_CONFIRMATIONS,
    TIER_STRONG_NOW_MIN,
    compute_confirmation_count,
)
from stonk_utils import atomic_write_json
import argparse
import logging
import subprocess
logger = logging.getLogger(__name__)

TIER_DISPLAY_MAP = {'STRONG_NOW': 'PRIME', 'NOW': 'BUILDING', 'WATCH': 'WATCHING', 'MONITOR': 'TRACKING'}

# High-beta basket config (matches risk_engine.py / trading_bot.py)
MAX_HIGH_BETA_DEPLOYED_PCT = 0.35
# Opportunistic headroom: exceptional PRIME candidates can queue above the steady cap.
OPPORTUNISTIC_HIGH_BETA_CAP = 0.40
HIGH_BETA_SPY_BETA_THRESHOLD = 1.2
HIGH_BETA_SPY_CORR_THRESHOLD = 0.70
CORRELATION_REPORT_PATH = Path("/var/www/hedge-fund-website/correlation_report.json")

# Diversification candidate thresholds (mirror paper_rebalancer.py / trading_bot.py)
DIVERSIFICATION_READINESS_MIN = 65.0
DIVERSIFICATION_CONFIRMATIONS_MIN = 2
DIVERSIFICATION_MAX_SECTOR_PCT = 0.30


def _symbol_sector(symbol: str) -> str:
    """Return sector mapping (synced with signal_engine.py / paper_rebalancer.py)."""
    sectors = {
        "Technology": ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "NFLX", "CRM", "ORCL", "ADBE", "INTU", "IBM", "INTC", "SNOW", "MDB", "GTLB", "CFLT", "ESTC", "PSTG", "DOCN", "VEEV", "TEAM", "NOW", "NET", "DDOG", "OKTA", "PATH", "PLTR", "UBER", "ABNB", "EXPE", "SPOT", "ROKU", "PINS", "SNAP", "TTD", "SHOP"],
        "Semiconductors": ["AMD", "MU", "LRCX", "AMAT", "KLAC", "SNPS", "CDNS", "MRVL", "NXPI", "QCOM", "SWKS", "TER", "ON", "AVGO", "TXN"],
        "Cybersecurity": ["CRWD", "PANW", "ZS", "FTNT", "CYBR", "S"],
        "Fintech": ["HOOD", "COIN", "SQ", "UPST", "AFRM", "SOFI", "PAYO", "LMND", "RELY", "PYPL", "FIS", "V", "GS", "MS", "BLK", "SCHW"],
        "Consumer/Platform": ["UBER", "DKNG", "SHOP", "TTD", "ROKU", "PINS", "SNAP", "ABNB", "EXPE", "SPOT", "ELF", "APP", "DUOL", "CHWY", "ETSY", "LULU", "NKE", "COST", "WMT", "HD"],
        "EV/Mobility": ["TSLA", "RIVN", "LCID", "NIO", "XPEV"],
        "Healthcare": ["UNH", "LLY", "JNJ", "PFE", "ABBV", "MRK", "TMO", "VRTX", "BMY", "REGN", "GILD", "ISRG", "ZBH", "ILMN", "SGEN"],
        "Energy": ["XOM", "CVX", "COP", "SLB", "EOG", "PSX", "MPC", "OXY"],
        "Industrials": ["GE", "CAT", "UNP", "HON", "UPS", "RTX", "LMT", "DE"],
        "Financials": ["JPM", "BAC", "WFC", "GS", "MS", "BLK", "SCHW", "V"],
        "Communications/Media": ["DIS", "CMCSA", "TMUS", "CHTR", "WBD", "PARA"],
    }
    for sector, symbols in sectors.items():
        if symbol in symbols:
            return sector
    return "Other"


def load_high_beta_symbols() -> set:
    """Load high-beta symbols from the correlation report."""
    try:
        data = json.loads(CORRELATION_REPORT_PATH.read_text())
        basket = set()
        for symbol, metrics in data.get("betas", {}).items():
            beta = metrics.get("spy")
            corr = metrics.get("spy_corr")
            if (beta is not None and beta > HIGH_BETA_SPY_BETA_THRESHOLD) or (corr is not None and corr > HIGH_BETA_SPY_CORR_THRESHOLD):
                basket.add(symbol)
        return basket
    except Exception as e:
        logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
        return set()

# Paths
SIGNALS_FILE = Path("/opt/stonk-ai/signals.json")
WATCHLIST_CHANGES_FILE = Path("/var/www/hedge-fund-website/watchlist_changes.json")
LIVE_WATCHLIST_FILE = Path("/var/www/hedge-fund-website/ai_watchlist_live.json")
WATCHLIST_META_FILE = Path("/var/www/hedge-fund-website/watchlist_meta.json")
TIER_HISTORY_FILE = Path("/opt/stonk-ai/tier_history.json")

# Config
MAX_WATCHLIST_SIZE = 20
TIER_BUILDING_MIN = 55.0  # floor for BUILDING tier


def load_signals() -> List[Dict]:
    """Load signals from the trading bot's signal engine output."""
    if not SIGNALS_FILE.exists():
        raise FileNotFoundError(f"Signals file not found: {SIGNALS_FILE}")
    with open(SIGNALS_FILE) as f:
        data = json.load(f)
    return data.get("signals", [])


def load_previous_watchlist() -> List[str]:
    """Load the previous watchlist symbols for change detection."""
    if not WATCHLIST_CHANGES_FILE.exists():
        return []
    try:
        with open(WATCHLIST_CHANGES_FILE) as f:
            data = json.load(f)
        return data.get("new_watchlist", [])
    except Exception as e:
        logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
        return []


def load_previous_tiers() -> Dict[str, str]:
    """Load previous tier assignments for change detection."""
    if not WATCHLIST_CHANGES_FILE.exists():
        return {}
    try:
        with open(WATCHLIST_CHANGES_FILE) as f:
            data = json.load(f)
        tiers = {}
        for tier_name, symbols in data.get("tiers", {}).items():
            for s in symbols:
                tiers[s] = tier_name
        return tiers
    except Exception as e:
        logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
        return {}


def assign_tier(backend_tier: str, entry_eligible: bool = False) -> str:
    """Map backend signal tier to website display tier.

    Deterministic mapping so the watchlist, monitor, and frontend all agree.
    """
    mapping = {
        "STRONG_NOW": "PRIME" if entry_eligible else "BUILDING",
        "NOW": "BUILDING",
        "WATCH": "WATCHING",
        "MONITOR": "TRACKING",
    }
    return mapping.get(backend_tier, "TRACKING")


def load_tier_history() -> List[Dict]:
    """Load tier change history."""
    if not TIER_HISTORY_FILE.exists():
        return []
    try:
        with open(TIER_HISTORY_FILE) as f:
            return json.load(f)
    except Exception as e:
        logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
        return []


def save_tier_history(history: List[Dict]):
    """Save tier change history."""
    try:
        with open(TIER_HISTORY_FILE, "w") as f:
            json.dump(history[-500:], f, indent=2)  # keep last 500 events
    except Exception as e:
        print(f"⚠️ Could not save tier history: {e}")


def detect_tier_changes(
    current_symbols: List[Dict],
    previous_tiers: Dict[str, str],
) -> List[Dict]:
    """Detect tier promotions and demotions."""
    changes = []
    now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    for sig in current_symbols:
        symbol = sig["symbol"]
        new_tier = sig.get("tier", "TRACKING")
        old_tier = previous_tiers.get(symbol)

        if old_tier and old_tier != new_tier:
            change_type = "promote" if (old_tier == "TRACKING" and new_tier in ("WATCHING", "BUILDING", "PRIME")) or (old_tier == "WATCHING" and new_tier in ("BUILDING", "PRIME")) or (old_tier == "BUILDING" and new_tier == "PRIME") else "demote"
            changes.append({
                "symbol": symbol,
                "change_type": change_type,
                "from_tier": old_tier,
                "to_tier": new_tier,
                "readiness_score": sig.get("readiness_score", 0),
                "reason": sig.get("tier_reason", ""),
                "timestamp": now,
            })

    return changes


def build_watchlist(signals: List[Dict]) -> Dict:

    """Build the watchlist update payload from ranked signals.
    Always fills to MAX_WATCHLIST_SIZE by backfilling from the universe."""
    from signal_engine import SignalEngine, DEFAULT_UNIVERSE, COMPANY_NAMES

    # Sort by readiness_score (primary), total_score (tiebreaker)
    signals.sort(key=lambda s: (s.get("readiness_score", 0), s.get("total_score", 0)), reverse=True)
    top = list(signals[:MAX_WATCHLIST_SIZE])

    current_symbols = [s["symbol"] for s in top]

    # Load held positions so they stay visible on the watchlist
    held_symbols = set()
    try:
        with open('/opt/stonk-ai/portfolio_data.json') as _pf:
            _portfolio = json.load(_pf)
        held_symbols = {p["symbol"] for p in _portfolio.get("positions", []) if p.get("symbol")}
    except Exception as e:
        logger.warning(f"Portfolio load failed: {type(e).__name__}: {e}")
        pass

    # Always include held positions in the watchlist
    # Build a lookup of all signals for held positions
    _all_signals_lookup = {s["symbol"]: s for s in signals}

    # Load previous watchlist to reuse real signal data for held positions
    _prev_prices = {}
    try:
        # REMOVED inner json import - use module-level json
        with open("/var/www/hedge-fund-website/ai_watchlist_live.json") as _f:
            _prev = json.load(_f)
        _prev_prices = _prev.get("prices", {})
        # Only reuse if previous data has real readiness_score (>0)
        _prev_prices = {k: v for k, v in _prev_prices.items() if v.get("readiness_score", 0) > 0}
    except Exception as e:
        logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
        pass
    for symbol in held_symbols:
        if symbol not in current_symbols:
            # Use actual signal data if available, otherwise reuse previous real data
            sig = _all_signals_lookup.get(symbol, {})
            if sig:
                # Copy signal data but mark as held
                held_sig = dict(sig)
                held_sig["tier_reason"] = "Held position — kept visible"
                held_sig["entry_eligible"] = False
                top.append(held_sig)
            elif symbol in _prev_prices:
                # Reuse previous real signal data (prevents 0.0 flapping when signal engine temporarily drops held positions)
                held_sig = dict(_prev_prices[symbol])
                held_sig["tier_reason"] = "Held position — kept visible"
                held_sig["entry_eligible"] = False
                top.append(held_sig)
            else:
                # Last-resort placeholder (no signal data found and no previous data to reuse)
                top.append({
                    "symbol": symbol,
                    "total_score": 0.0,
                    "readiness_score": 0.0,
                    "momentum_score": 0.0,
                    "quality_score": 0.0,
                    "risk_score": 0.0,
                    "regime_score": 0.0,
                    "tier": "MONITOR",
                    "entry_eligible": False,
                    "confirmation_count": 0,
                    "tier_reason": "Held position — kept visible",
                    "rank": 0,
                    "price": 0.0,
                    "atr14": 0.0,
                    "rsi14": 50.0,
                    "momentum_20d": 0.0,
                    "momentum_50d": 0.0,
                    "volatility_20d": 0.0,
                    "avg_volume": 0,
                    "spy_corr_20d": 0.0,
                    "ai_score": None,
                    "sector": SignalEngine._sector(symbol),
                    "company": COMPANY_NAMES.get(symbol, symbol),
                    "confirmations": {},
                })
            current_symbols.append(symbol)

    # ── Validation: held positions must survive ──
    try:
        with open('/opt/stonk-ai/portfolio_data.json') as _pf:
            _portfolio_check = json.load(_pf)
        _held_check = {p["symbol"] for p in _portfolio_check.get("positions", []) if p.get("symbol")}
        _watchlist_syms = {s["symbol"] for s in top}
        _missing = _held_check - _watchlist_syms
        if _missing:
            logger.error(f"HELD_POSITION_MISSING: {_missing} — portfolio has them but watchlist dropped them")
    except Exception as e:
        logger.warning(f"Held position validation failed: {type(e).__name__}: {e}")
        pass

    # Backfill to ensure exactly MAX_WATCHLIST_SIZE names
    signal_symbols = set(current_symbols)
    backfill_syms = []
    for symbol in DEFAULT_UNIVERSE:
        if len(backfill_syms) >= MAX_WATCHLIST_SIZE - len(top):
            break
        if symbol in signal_symbols or symbol in held_symbols:
            continue
        backfill_syms.append(symbol)

    # Batch fetch real prices for backfill stocks via Alpaca data hub
    backfill_prices = {}
    if backfill_syms:
        try:
            _hub = get_data_hub()
            backfill_prices = _hub.get_latest_prices(backfill_syms)
        except Exception as _e:
            print(f"Warning: could not fetch backfill prices: {_e}")

    for symbol in backfill_syms:
        _price = backfill_prices.get(symbol, 0.0)
        # Add a placeholder signal so the watchlist stays at 15 names
        top.append({
            "symbol": symbol,
            "total_score": 0.0,
            "readiness_score": 0.0,
            "momentum_score": 0.0,
            "quality_score": 0.0,
            "risk_score": 0.0,
            "regime_score": 0.0,
            "tier": "TRACKING",
            "entry_eligible": False,
            "confirmation_count": 0,
            "tier_reason": "Universe tracking",
            "rank": 0,
            "price": _price,
            "atr14": 0.0,
            "rsi14": 50.0,
            "momentum_20d": 0.0,
            "momentum_50d": 0.0,
            "volatility_20d": 0.0,
            "avg_volume": 0,
            "spy_corr_20d": 0.0,
            "ai_score": None,
            "sector": SignalEngine._sector(symbol),
            "company": COMPANY_NAMES.get(symbol, symbol),
            "confirmations": {},
        })
        current_symbols.append(symbol)

    # ── Fetch extended hours data (pre-market + after-hours) ──
    ext_hours_data = {}
    try:
        _hub_ext = get_data_hub()
        ext_hours_data = _hub_ext.get_extended_hours_bars(current_symbols)
        print(f"Extended hours data for {len(ext_hours_data)} symbols")
    except Exception as _e:
        print(f"Warning: could not fetch extended hours data: {_e}")

    # ── Fetch live snapshot data for intraday range/high/low/volume ──
    snap_data = {}
    try:
        _hub_snap = get_data_hub()
        snap_data = _hub_snap.get_snapshots(current_symbols)
        print(f"Snapshot data for {len(snap_data)} symbols")
    except Exception as _e:
        print(f"Warning: could not fetch snapshot data: {_e}")

    previous = load_previous_watchlist()
    previous_tiers = load_previous_tiers()
    added = [s for s in current_symbols if s not in previous]
    removed = [s for s in previous if s not in current_symbols]
    kept = [s for s in current_symbols if s in previous]

    # User-friendly display tier labels. Action-based:
    # PRIME = entry_eligible, BUILDING/WATCHING = scored but not eligible, TRACKING = < 55
    DISPLAY_TIER = {
        "PRIME": "PRIME",
        "BUILDING": "BUILDING",
        "WATCHING": "WATCHING",
        "TRACKING": "TRACKING",
    }

    # Build tiers from action-based tier
    tiers = {"PRIME": [], "BUILDING": [], "WATCHING": [], "TRACKING": []}
    for s in top:
        readiness = s.get("readiness_score", 0)
        total_score = s.get("total_score", 0)
        is_scored = total_score > 0 or readiness > 0
        tier = assign_tier(s.get("tier", "MONITOR"), s.get("entry_eligible", False)) if is_scored else "TRACKING"
        tiers[tier].append(s["symbol"])

    # Detect tier changes
    tier_changes = detect_tier_changes(top, previous_tiers)

    # Save tier history
    tier_history = load_tier_history()
    tier_history.extend(tier_changes)
    save_tier_history(tier_history)

    # Build live watchlist price data in the format the website expects
    prices = {}
    for s in top:
        symbol = s["symbol"]
        readiness = s.get("readiness_score", 0)
        total_score = s.get("total_score", 0)
        is_scored = total_score > 0 or readiness > 0
        tier = assign_tier(s.get("tier", "MONITOR"), s.get("entry_eligible", False)) if is_scored else "TRACKING"
        price = s.get("price", 0)
        # Fall back to prev_close when no live price (market closed)
        if not price or price == 0:
            price = s.get("prev_close", 0) or 0
        change_pct = round(s.get("momentum_20d", 0) * 100, 2)
        change_amount = round(price * change_pct / 100, 2) if price else 0
        rsi = s.get("rsi14", 50)
        # Map readiness to ai_score for website compatibility
        ai_score = int(min(100, max(30, readiness))) if is_scored else 40
        sentiment = 50
        sentiment_label = "Neutral"
        volume = s.get("avg_volume", 0)
        avg_volume = volume

        # Conservative/aggressive targets for website compatibility
        conservative_target = round(price * 1.08, 2) if price else 0
        aggressive_target = round(price * 1.12, 2) if price else 0
        stop_loss = round(price * 0.90, 2) if price else 0
        profit_25 = round(price * 1.25, 2) if price else 0
        profit_50 = round(price * 1.50, 2) if price else 0

        # Compute action-based tier
        entry_eligible = s.get("entry_eligible", False)
        conf_count = compute_confirmation_count(s.get("confirmations", {}))
        raw_reason = s.get("tier_reason", f"Readiness {readiness:.1f}")
        tier_reason = raw_reason
        if tier_reason.startswith("STRONG_NOW:"):
            tier_reason = "PRIME:" + tier_reason[len("STRONG_NOW:"):]
        elif tier_reason.startswith("NOW:"):
            tier_reason = "BUILDING:" + tier_reason[len("NOW:"):]
        elif tier_reason.startswith("WATCH:"):
            tier_reason = "WATCHING:" + tier_reason[len("WATCH:"):]
        elif tier_reason.startswith("MONITOR:"):
            tier_reason = "TRACKING:" + tier_reason[len("MONITOR:"):]
        tier = assign_tier(s.get("tier", "MONITOR"), entry_eligible)
        # Build council note from action tier
        if not is_scored:
            council_note = "Universe tracking"
        elif tier == "PRIME":
            council_note = f"PRIME | Readiness {readiness:.1f} | {conf_count}/10 conf | ENTRY READY"
        elif tier == "BUILDING":
            council_note = f"BUILDING | Readiness {readiness:.1f} | {conf_count}/10 conf | building strength, not entry eligible"
        elif tier == "WATCHING":
            council_note = f"WATCHING | Readiness {readiness:.1f} | {conf_count}/10 conf | watching, not entry eligible"
        else:
            council_note = f"TRACKING | Readiness {readiness:.1f} | {conf_count}/10 conf | below watching threshold"

        targets = {
            "target": symbol,
            "signal": tier,
            "score": round(readiness, 1),
            "confidence": 0,
            "conservative_target": conservative_target,
            "aggressive_target": aggressive_target,
            "stop_loss": stop_loss,
            "position_size": None,
            "profit_25": profit_25,
            "profit_50": profit_50,
            "rationale": tier_reason,
            "entry_eligible": entry_eligible,
            "confirmations": conf_count,
            "council_note": council_note,
            "symbol": symbol,
            "display_tier": tier,
        }

        snap = snap_data.get(symbol, {})
        daily_vwap = s.get("daily_vwap") or snap.get("daily_vwap")
        daily_high = snap.get("daily_high") or s.get("daily_high")
        daily_low = snap.get("daily_low") or s.get("daily_low")
        prev_close = s.get("prev_close") or snap.get("prev_close")
        if snap.get("daily_volume"):
            volume = snap["daily_volume"]
            avg_volume = s.get("avg_volume", 0)
        # If we have prev_close, compute real change from it
        if prev_close and prev_close > 0 and price:
            change_pct = round((price - prev_close) / prev_close * 100, 2)
            change_amount = round(price - prev_close, 2)
        if daily_vwap and daily_vwap > 0 and price:
            # Use real bid/ask spread relative to VWAP instead of synthetic
            vwap_dev = (price - daily_vwap) / daily_vwap
        # Merge extended hours data if signal doesn't already have it
        ext = ext_hours_data.get(symbol, {})
        premarket_change = s.get("premarket_change_pct") if s.get("premarket_change_pct") is not None else ext.get("premarket_change_pct")
        premarket_vol = s.get("premarket_volume") if s.get("premarket_volume") is not None else ext.get("premarket_volume")
        afterhours_change = s.get("afterhours_change_pct") if s.get("afterhours_change_pct") is not None else ext.get("afterhours_change_pct")
        afterhours_vol = s.get("afterhours_volume") if s.get("afterhours_volume") is not None else ext.get("afterhours_volume")

        display_tier_name = TIER_DISPLAY_MAP.get(tier, tier)
        prices[symbol] = {
            "price": price,
            "change_pct": change_pct,
            "change_amount": change_amount,
            "rsi": rsi,
            "bid": round(price * 0.999, 2) if price else 0,
            "ask": round(price * 1.001, 2) if price else 0,
            "volume": volume,
            "avg_volume": avg_volume,
            "ai_score": ai_score,
            "sentiment": sentiment,
            "sentiment_label": sentiment_label,
            "total_score": total_score,
            "readiness_score": readiness,
            "momentum_score": s.get("momentum_score", 0),
            "daily_vwap": daily_vwap,
            "daily_high": daily_high,
            "daily_low": daily_low,
            "prev_close": prev_close,
            "intraday_vwap": s.get("intraday_vwap"),
            "intraday_vol_ratio": s.get("intraday_vol_ratio"),
            "momentum_5m_up": s.get("momentum_5m_up", False),
            "volume_5m_surge": s.get("volume_5m_surge", False),
            "price_above_5m_vwap": s.get("price_above_5m_vwap", False),
            "intraday_5m_return": s.get("intraday_5m_return"),
            "intraday_5m_vwap": s.get("intraday_5m_vwap"),
            "options_implied_vol": s.get("options_implied_vol"),
            "options_volume": s.get("options_volume"),
            "options_call_put_ratio": s.get("options_call_put_ratio"),
            "options_unusual_volume": s.get("options_unusual_volume", False),
            "near_term_bullish_flow": s.get("near_term_bullish_flow", False),
            "options_flow_score": s.get("options_flow_score", 50.0),
            "bid_ask_spread_pct": s.get("bid_ask_spread_pct"),
            "wide_spread": s.get("wide_spread", False),
            "spread_ok": s.get("spread_ok", True),
            "bid_ask_imbalance": s.get("bid_ask_imbalance"),
            "bid_ask_bullish": s.get("bid_ask_bullish", False),
            "has_upcoming_dividend": s.get("has_upcoming_dividend", False),
            "has_upcoming_split": s.get("has_upcoming_split", False),
            "has_upcoming_merger": s.get("has_upcoming_merger", False),
            "has_upcoming_spinoff": s.get("has_upcoming_spinoff", False),
            "corporate_action_risk": s.get("corporate_action_risk", False),
            "no_corporate_action_risk": not s.get("corporate_action_risk", False),
            "momentum_20d": s.get("momentum_20d"),
            "momentum_50d": s.get("momentum_50d"),
            "regime_score": s.get("regime_score"),
            "volatility_20d": s.get("volatility_20d"),
            "strategy_type": s.get("strategy_type", "momentum"),
            "atr14": s.get("atr14"),
            "spy_corr_20d": s.get("spy_corr_20d"),
                        "quality_score": s.get("quality_score", 0),
            "risk_score": s.get("risk_score", 0),
            "regime_score": s.get("regime_score", 0),
            "sector": s.get("sector", "Other"),
            "company": s.get("company", COMPANY_NAMES.get(symbol, symbol)),
            "is_scored_signal": is_scored,
            "signal_tier": tier,
            "signal": tier,
            "display_tier": display_tier_name,
            "backend_tier": s.get("tier") or "MONITOR",
            "entry_eligible": entry_eligible,
            "confirmation_count": conf_count,
            "confirmations": s.get("confirmations", {}),
            "factor_breakdown": s.get("factor_breakdown", {}),
            "tier_reason": tier_reason,
            "targets": targets,
            "premarket_change_pct": premarket_change,
            "premarket_volume": premarket_vol,
            "afterhours_change_pct": afterhours_change,
            "afterhours_volume": afterhours_vol,
        }

    # Ensure display_tier / backend_tier are set on all price dicts (frontend fallback)
    for symbol, pdata in prices.items():
        if "display_tier" not in pdata:
            pdata["display_tier"] = pdata.get("signal_tier", "TRACKING")
        if "backend_tier" not in pdata or pdata["backend_tier"] is None:
            pdata["backend_tier"] = assign_tier(pdata.get("signal_tier"), pdata.get("entry_eligible", False))

    # Compute buy candidates: mirrors the bot's first-order entry gate
    # Load current portfolio positions and weights
    portfolio_positions = {}
    portfolio_value = 0.0
    portfolio = {}
    try:
        portfolio = json.loads(Path("/var/www/hedge-fund-website/portfolio_data.json").read_text())
        # Prefer total account value (cash + equity), then fall back to legacy fields
        portfolio_value = float(
            portfolio.get("account", {}).get("portfolio_value")
            or portfolio.get("total_value")
            or portfolio.get("portfolio_value")
            or 0
        )
        positions = portfolio.get("positions", [])
        # If no explicit total, sum market values
        if not portfolio_value:
            portfolio_value = sum(float(p.get("market_value", 0) or 0) for p in positions)
        for p in positions:
            sym = p.get("symbol")
            if not sym:
                continue
            mv = float(p.get("market_value", 0) or 0)
            portfolio_positions[sym] = {"market_value": mv, "weight": (mv / portfolio_value * 100) if portfolio_value else 0}
    except Exception as e:
        logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
        pass
    # Target weight threshold: under this, a held eligible position is an "add" candidate
    ADD_WEIGHT_THRESHOLD = 6.0  # percent of portfolio

    # High-beta basket guard for Next Buys display
    high_beta_symbols = load_high_beta_symbols()
    if portfolio_value > 0:
        high_beta_mv = sum(p.get("market_value", 0) for p in portfolio.get("positions", []) if p.get("symbol") in high_beta_symbols)
        high_beta_pct = high_beta_mv / portfolio_value
    else:
        high_beta_pct = 0.0

    # Sector exposures for diversification status
    sector_exposures = {}
    if portfolio:
        for p in portfolio.get("positions", []):
            sector = _symbol_sector(p.get("symbol"))
            sector_exposures[sector] = sector_exposures.get(sector, 0.0) + p.get("market_value", 0)

    # Precompute over-cap flag so held high-beta positions can surface it too
    high_beta_over_cap = high_beta_pct > MAX_HIGH_BETA_DEPLOYED_PCT

    buy_candidates = []
    for symbol, pdata in prices.items():
        tier = pdata.get("signal_tier", "TRACKING")
        entry_eligible = pdata.get("entry_eligible", False)
        price = pdata.get("price", 0)
        readiness = pdata.get("readiness_score", 0)
        held_info = portfolio_positions.get(symbol)
        is_high_beta = symbol in high_beta_symbols

        if held_info:
            if entry_eligible and held_info.get("weight", 0) < ADD_WEIGHT_THRESHOLD:
                status = "add"
                reason = f"Held, underweight ({held_info['weight']:.1f}%) and still eligible"
            elif is_high_beta and high_beta_over_cap:
                status = "hold"
                reason = f"Held at {held_info['weight']:.1f}% — high-beta basket over cap ({high_beta_pct:.1%})"
            else:
                status = "hold"
                reason = f"Held at {held_info['weight']:.1f}% — no add planned"
        elif is_high_beta and high_beta_pct >= MAX_HIGH_BETA_DEPLOYED_PCT:
            # Opportunistic headroom: exceptional PRIME candidates may queue up to the higher cap
            if tier == "PRIME" and readiness >= TIER_STRONG_NOW_MIN and high_beta_pct <= OPPORTUNISTIC_HIGH_BETA_CAP:
                status = "queued"
                reason = f"Queued (opportunistic high-beta, basket {high_beta_pct:.1%})"
            else:
                status = "high_beta_blocked"
                reason = f"High-beta basket at {high_beta_pct:.1%} (cap {MAX_HIGH_BETA_DEPLOYED_PCT:.1%})"
        elif not entry_eligible:
            status = "not_ready"
            reason = f"Readiness {readiness:.1f} / {pdata.get('confirmation_count', 0)} confirmations"
        elif tier not in ("PRIME",):
            status = "tier_too_low"
            reason = f"Tier {tier} below entry gate"
        elif not price or price <= 0:
            status = "no_price"
            reason = "No live price"
        else:
            status = "queued"
            reason = "Queued for next cycle"
        buy_candidates.append({
            "symbol": symbol,
            "display_tier": TIER_DISPLAY_MAP.get(tier, tier),
            "tier": tier,
            "status": status,
            "reason": reason,
            "readiness_score": readiness,
            "confirmation_count": pdata.get("confirmation_count", 0),
            "entry_eligible": entry_eligible,
            "weight_pct": held_info.get("weight", 0) if held_info else 0,
        })

    # Unify buy_status/reason into each symbol's price dict so consumers don't need to cross-reference buy_candidates
    candidate_status_by_symbol = {c["symbol"]: c for c in buy_candidates}
    for symbol, pdata in prices.items():
        cdata = candidate_status_by_symbol.get(symbol, {})
        pdata["buy_status"] = cdata.get("status")
        pdata["buy_status_reason"] = cdata.get("reason")

    update_log = {
        "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "source": "signals.json",
        "added": [{"symbol": a, "reason": "Top readiness score"} for a in added],
        "removed": [{"symbol": r, "reason": "Fell out of top readiness"} for r in removed],
        "new_watchlist": current_symbols,
        "kept": kept,
        "tiers": tiers,
        "tier_changes": tier_changes,
        "buy_candidates": buy_candidates,
        "summary": {
            "total": len(current_symbols),
            "prime_count": len(tiers["PRIME"]),
            "building_count": len(tiers["BUILDING"]),
            "tracking_count": len(tiers["TRACKING"]),
            "added_count": len(added),
            "removed_count": len(removed),
            "tier_changes_count": len(tier_changes),
            "queued_count": sum(1 for c in buy_candidates if c["status"] == "queued"),
            "held_count": sum(1 for c in buy_candidates if c["status"] == "held"),
        },
    }

    live_data = {
        "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "prices": prices,
        "buy_candidates": buy_candidates,
        "signals_source": str(SIGNALS_FILE),
    }

    return {
        "watchlist_changes": update_log,
        "live_watchlist": live_data,
    }


def write_outputs(payload: Dict, dry_run: bool = False):
    """Write watchlist files for the website (or skip writes if dry_run)."""
    WATCHLIST_CHANGES_FILE.parent.mkdir(parents=True, exist_ok=True)
    LIVE_WATCHLIST_FILE.parent.mkdir(parents=True, exist_ok=True)

    live_data = payload["live_watchlist"]
    prices = live_data.get("prices", {})
    if len(prices) > MAX_WATCHLIST_SIZE:
        logger.warning(f"Watchlist has {len(prices)} symbols; truncating to {MAX_WATCHLIST_SIZE}")
        # Protect held positions from being dropped
        held_symbols = set()
        try:
            with open('/opt/stonk-ai/portfolio_data.json') as _pf:
                _portfolio = json.load(_pf)
            held_symbols = {p["symbol"] for p in _portfolio.get("positions", []) if p.get("symbol")}
        except Exception as e:
            logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
            pass
        # Always keep held symbols; fill remaining slots by ai_score
        non_held = [s for s in prices.keys() if s not in held_symbols]
        non_held.sort(key=lambda s: prices[s].get("ai_score", 0), reverse=True)
        remaining_slots = max(0, MAX_WATCHLIST_SIZE - len(held_symbols))
        kept = list(held_symbols) + non_held[:remaining_slots]
        live_data["prices"] = {s: prices[s] for s in kept}
        # Also truncate buy_candidates to symbols in kept prices if present
        if "buy_candidates" in live_data:
            live_data["buy_candidates"] = [c for c in live_data["buy_candidates"] if c.get("symbol") in live_data["prices"]]

    if dry_run:
        print(f"[DRY RUN] Would write {WATCHLIST_CHANGES_FILE}")
    else:
        with open(WATCHLIST_CHANGES_FILE, "w") as f:
            json.dump(payload["watchlist_changes"], f, indent=2)

    # Also write canonical watchlist array for consumers expecting \"watchlist\" key
    watchlist_prices = list(live_data["prices"].values())
    for sym, item in zip(live_data["prices"].keys(), watchlist_prices):
        item["symbol"] = sym
    live_data["watchlist"] = watchlist_prices
    with open(LIVE_WATCHLIST_FILE, "w") as f:
        json.dump(live_data, f, indent=2)

    # Atomic write to /opt/stonk-ai/ so downstream consumers (monitor, heartbeat) stay in sync
    OPT_WATCHLIST_FILE = Path("/opt/stonk-ai/ai_watchlist_live.json")
    if dry_run:
        print(f"[DRY RUN] Would write {LIVE_WATCHLIST_FILE} and {OPT_WATCHLIST_FILE}")
    else:
        try:
            atomic_write_json(OPT_WATCHLIST_FILE, live_data, owner="stonkai")
        except Exception as e:
            print(f"⚠️ Failed to write opt watchlist file: {e}")


def update_watchlist(dry_run: bool = False):
    print(f"\n🔄 Watchlist Sync — {datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')}")
    signals = load_signals()
    if not signals:
        print("⚠️ No signals found. Skipping watchlist update.")
        return

    payload = build_watchlist(signals)
    write_outputs(payload, dry_run=dry_run)

    wc = payload["watchlist_changes"]
    print(f"📊 Watchlist: {wc['summary']['total']} symbols")
    print(f"  🚀 PRIME ({len(wc['tiers']['PRIME'])}): {', '.join(wc['tiers']['PRIME']) if wc['tiers']['PRIME'] else 'None'}")
    print(f"  🔥 BUILDING ({len(wc['tiers']['BUILDING'])}): {', '.join(wc['tiers']['BUILDING']) if wc['tiers']['BUILDING'] else 'None'}")
    print(f"  🔍 TRACKING ({len(wc['tiers']['TRACKING'])}): {', '.join(wc['tiers']['TRACKING']) if wc['tiers']['TRACKING'] else 'None'}")
    if wc["added"]:
        print(f"  ➕ Added: {', '.join(a['symbol'] for a in wc['added'])}")
    if wc["removed"]:
        print(f"  ➖ Removed: {', '.join(r['symbol'] for r in wc['removed'])}")
    if wc.get("tier_changes"):
        for tc in wc["tier_changes"]:
            print(f"  {'⬆️' if tc['change_type'] == 'promote' else '⬇️'} {tc['symbol']}: {tc['from_tier']} → {tc['to_tier']} ({tc['reason']})")
    if dry_run:
        print(f"[DRY RUN] Skipped writing to {WATCHLIST_CHANGES_FILE} and {LIVE_WATCHLIST_FILE}\n")
    else:
        print(f"💾 Written to {WATCHLIST_CHANGES_FILE} and {LIVE_WATCHLIST_FILE}\n")


def _record_heartbeat():
    try:
        subprocess.run(
            ["/usr/bin/python3", "/opt/stonk-ai/heartbeat_tracker.py", "dynamic_watchlist_manager"],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except Exception as e:
        logger.warning(f"Silent error suppressed: {type(e).__name__}: {e}")
        pass
def _parse_args():
    parser = argparse.ArgumentParser(description="Dynamic Watchlist Manager")
    parser.add_argument("--dry-run", action="store_true", help="Run without writing files")
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    update_watchlist(dry_run=args.dry_run)
    _record_heartbeat()